
package ec.gob.sri.ws.recepcion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import recepcion.ws.sri.gob.ec.ObjectFactory;
import recepcion.ws.sri.gob.ec.RespuestaSolicitud;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebService(name = "RecepcionComprobantesOffline", targetNamespace = "http://ec.gob.sri.ws.recepcion")
@XmlSeeAlso({ ObjectFactory.class })
public interface RecepcionComprobantesOffline {


    /**
     *
     * @param xml
     * @return
     *     returns recepcion.ws.sri.gob.ec.RespuestaSolicitud
     */
    @WebMethod
    @WebResult(name = "RespuestaRecepcionComprobante", targetNamespace = "")
    @RequestWrapper(localName = "validarComprobante", targetNamespace = "http://ec.gob.sri.ws.recepcion",
                    className = "recepcion.ws.sri.gob.ec.ValidarComprobante")
    @ResponseWrapper(localName = "validarComprobanteResponse", targetNamespace = "http://ec.gob.sri.ws.recepcion",
                     className = "recepcion.ws.sri.gob.ec.ValidarComprobanteResponse")
    public RespuestaSolicitud validarComprobante(@WebParam(name = "xml", targetNamespace = "") byte[] xml);

}
